### ISSUE TITLE
Double-reading each line

### ISSUE THREAD

**Issue by anson-vandoren** [srobinson2018/log-collection#5]
It appears that the loop in `server/parser.go` is essentially reading through each line twice - once by character, only looking for a linebreak, then a second time to actually read in the line. You might consider an alternative approach that allows you to read in chunks of the file at a time, then do your line-splitting in memory to avoid the performance hit of doing file IO twice for each line.

**Comment by srobinson2018** [comment]
Great idea! I actually just tried out a different approach where I was using a buffer to read through the file thinking that may shave off some time but it resulted in worst performance due to slice resizing. May be a viable solution if I instead used a defined buffer but then the code would have to manually resize the array for longer log lines.

I will give the chunking approach a shot!

**Comment by srobinson2018** [comment]
As I was implementing it I realized that this is generally how file readers work. Reminded me of Java's `BufferedReader`. I have it working with a buffered read and now have it running **way** faster. I am going to add some CLI parameters to allow for easily adjusting the buffer size and then make a PR.

**Comment by srobinson2018** [comment]
Opened up (and merged) [this PR](https://github.com/srobinson2018/log-collection/pull/11) that added the streaming logic 👍

**Comment by anson-vandoren** [comment]
@srobinson2018 thanks! Performance looking a lot better now on my test files. very minor nit left here: is 128 the best value for a default, or can you get better performance out-of-the-box with a different value?

**Comment by srobinson2018** [comment]
I did not do much tuning to determine the best default value since I added it to the API as a query param along the thinking that the consumer would have the opportunity to tune the request to their needs.

In a production environment, we would need to tune it a bit or add some limits to the buffer size (or maybe remove the ability to set it via API) in order to offert more predictable performance and resource requirements for scaling.
